input_modality_channels:
  - 25
  - 35
  - 512
  - 256
  - 1024
output_dim:
  - 1
d_model: 40
n_heads: 8
n_layers: 6
attention_type: linear
dropout_embedding: 0
dropout_ca: 0.1
dropout_sa: 0.1
dropout_relu: 0.1
dropout_residual: 0.1
dropout_output: 0.1
time_reduce_type: gap
add_ffn_fusion: True