accelerator: gpu
devices:
- 1
float32_matmul_precision: medium # high, highest
output_dir: training_results_mosi/
n_epochs: 20
loss_fn: bell_l2_l1_loss
base_lr: 0.001
optimizer: radam
weight_decay: 1e-5
decoupled_weight_decay: True
lr_scheduler: cosine_warmup
warmup_steps: 0.05 # 5%