input_modality_channels:
  - 25
  - 35
  - 512
  - 256
  - 1024
output_dim:
  - 5
d_model: 32
n_heads: 8
n_layers: 5
attention_type: linear
dropout_embedding: 0
dropout_ca: 0.2
dropout_sa: 0.2
dropout_relu: 0.2
dropout_residual: 0.2
dropout_output: 0.2
time_reduce_type: last
add_ffn_fusion: True