db_name: MOSI
db_root: data/db_processed/mosi
seed: 42

feature_list:
  - egemaps_lld # (T_a, 25) openSMILE eGeMAPS LLD
  - opengraphau # (T_v, 41) OpenGraphAU
  - bert # (T_t, 768) BERT

train_size: 1284
valid_size: 229
test_size: 686

batch_size: 16
num_workers: 3